### ISSUE TITLE
How do you access the resulting data.table?

### ISSUE THREAD

**Issue by iembry** [bogind/easycsv#5]
Hi, I am using the fread_folder function of your `easycsv` package, but I am unable to access the resulting data.table.

For example,

```
> vir <- fread_folder("folder_name")
> vir 
  NULL
```

How do you access the resulting data.table? Will you add some examples?

Thank you.

**Comment by bogind** [comment]
You don't need to set the variable. Just use:
`fread_folder('path to your folder')`
And you will get data.table's with the names of the files you had in your folder.
Closing as this is not an issue.

**Comment by iembry** [comment]
@bogind  Thank you for the explanation. It would help if you would place that statement on the README. I didn't read the README well enough as I had thought that `easycsv` would create a single `data.table` or `data.frame` from the CSV files in the folder. That's what I was after with this package.
